name: Run lint and type checks

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
   runs-on: ubuntu-latest    

   steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
       node-version: 20
    - run: npm i -g pnpm@9
    - run: rm -rf node_modules
    - run: pnpm i
    - run: pnpm run check-types
    - run: pnpm run lint